export { default as Comparison } from './Comparison/Comparison.page'
export { default as Favourites } from './Favourites/Favourites.page'
export { default as HomePage } from './Home/Home.page'
export { default as PokemonDetails } from './PokemonDetail/PokemonDetails.page'
export { default as ErrorPage } from './ErrorPage/ErrorPage'