export default {
    spriteFallBack: require('./spriteFallbackIcon.png'),
    bugType: require('./type_BUG.png'),
    darkType: require('./type_DARK.png'),
    dragonType: require('./type_DRAGON.png'),
    electricType: require('./type_ELECTRIC.png'),
    fairyType: require('./type_FAIRY.png'),
    fightingType: require('./type_FIGHTING.png'),
    fireType: require('./type_FIRE.png'),
    flyingType: require('./type_FLYING.png'),
    ghostType: require('./type_GHOST.png'),
    grassType: require('./type_GRASS.png'),
    groundType: require('./type_GROUND.png'),
    iceType: require('./type_ICE.png'),
    normalType: require('./type_NORMAL.png'),
    poisonType: require('./type_POISON.png'),
    psychicType: require('./type_PSYCHIC.png'),
    rockType: require('./type_ROCK.png'),
    steelType: require('./type_STEEL.png'),
    waterType: require('./type_WATER.png'),
}